###############################################################
### Default configuration for development environment.      ###
### In test/production this file will be used but will be   ###
### extended with tes.yml or production.yml                 ###
###############################################################
version: '3'
services:
    eureka:
        build: ../eureka-server
        ports:
        - "8761:8761"
        networks:
            - my-network

    hystrixdashboard:
        build: ../hystrix-dashboard
        links:
        - turbine
        ports:
        - "7979:7979"
        networks:
            - my-network

    configservice:
        build: ../config-service
        expose:
        - "8888"
        ports:
        - "8888:8888"
        networks:
            - my-network

    #springbootadmin:
    #    build: ../spring-boot-admin
    #    ports:
    #     - "8085:8085"

    springclouddashboard:
        build: ../spring-cloud-dashboard
        environment:
        - spring.profiles.active=docker
        links:
        - eureka
        - turbine
        - configservice
        ports:
        - "8086:8086"
        networks:
            - my-network

    turbine:
        build: ../turbine
        environment:
        - spring.profiles.active=docker
        links:
        - configservice
        - rabbitmq
        ports:
        - "8989:8989"
        networks:
            - my-network

    zuul:
        build: ../zuul
        ports:
        - "8765:8765"
        networks:
            - my-network

    rabbitmq:
        image: rabbitmq:3.5.3-management
        expose:
        - "5672"
        ports:
        - "5672:5672"
        networks:
            - my-network

    servicea:
        build: ../service_a
        environment:
        - spring.profiles.active=docker
        links:
        - configservice
        - eureka
        - rabbitmq
        networks:
            - my-network

    # serviceb:
    #     build: ../service_b
    #     environment:
    #     - spring.profiles.active=docker
    #     links:
    #     - configservice
    #     - eureka
    #     - rabbitmq
    #     networks:
    #         - my-network

    # servicec:
    #     build: ../service_c
    #     environment:
    #     - spring.profiles.active=docker
    #     links:
    #     - configservice
    #     - eureka
    #     - rabbitmq
    #     networks:
    #         - my-network

    # clienttrafficgenerator:
    #     build: ../client-traffic-generator
    #     environment:
    #      - spring.profiles.active=docker
    #     links:
    #      - configservice
    #      - eureka
    #      - rabbitmq

networks:
    my-network: